#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT '$APP_USERNAME';
    CREATE USER $APP_USERNAME WITH
        LOGIN
        ENCRYPTED PASSWORD '$APP_PASSWORD'
        NOSUPERUSER
        INHERIT
        NOCREATEDB
        NOCREATEROLE
        NOREPLICATION
        VALID UNTIL 'infinity';
    CREATE DATABASE $APP_DATABASE;
EOSQL