#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DATABASE" <<-EOSQL
    GRANT SELECT,INSERT ON TABLE public.fact_type TO $APP_USERNAME;
    GRANT SELECT, USAGE ON SEQUENCE fact_type_fact_type_id_seq TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.role TO $APP_USERNAME;
    GRANT SELECT, USAGE ON SEQUENCE role_role_id_seq TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.fact TO $APP_USERNAME;
    GRANT SELECT, USAGE ON SEQUENCE fact_fact_id_seq TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.edge TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.ancestor TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.public_key TO $APP_USERNAME;
    GRANT SELECT, USAGE ON SEQUENCE public_key_public_key_id_seq TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.signature TO $APP_USERNAME;
    GRANT SELECT,INSERT ON TABLE public.user TO $APP_USERNAME;
EOSQL